checkpoint:
  save:
    save_dir: D:\ScientificResearch\Paper_Project\SI\weight\nanseg
    is_save_checkpoint: False
  load:
    load_dir: D:\ScientificResearch\Paper_Project\SI\weight\nanseg\all_sum_best_model.pth
    is_load_checkpoint: False

model:
  backbone:
    name: UNet
    in_channels: 1
    num_classes: 30
    base_c: 64
    pointnet: True
    isGroupNorm: True
    num_gropus: 32
    is_point: True
  fusion:
    name: PFF
    num_classes: 30
    isGroupNorm: True
    num_gropus: 32

data:
  train:
    datas_dir: E:\datesets\HaNSeg\SI\train
  val:
    datas_dir: E:\datesets\HaNSeg\SI\val
  transforms:
    Crop_w: 128
    Crop_h: 128

schedule:
  optimizer_unet:
    name: AdamW
    lr: 0.0001
    momentum: 0.9
    weight_decay: 0.5
  optimizer_pff:
    name: AdamW
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.5
  total_epochs: 1000
  batch_size: 1
  lr_scheduler:
    name: ReduceLROnPlateau
    mode: max
    patience: 5
    threshold: 0.0001

labels:
  - A_Carotid_L
  - A_Carotid_R
  - Arytenoid
  - Bone_Mandible
  - Brainstem
  - BuccalMucosa
  - Cavity_Oral
  - Cochlea_L
  - Cochlea_R
  - Cricopharyngeus
  - Esophagus_S
  - Eye_AL
  - Eye_AR
  - Eye_PL
  - Eye_PR
  - Glnd_Lacrimal_L
  - Glnd_Lacrimal_R
  - Glnd_Submand_L
  - Glnd_Submand_R
  - Glnd_Thyroid
  - Glottis
  - Larynx_SG
  - Lips
  - OpticChiasm
  - OpticNrv_L
  - OpticNrv_R
  - Parotid_L
  - Parotid_R
  - Pituitary
  - SpinalCord
